# Generated by Django 5.0.6 on 2024-05-18 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Girls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subname', models.CharField(default='Default Subname', max_length=100)),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Ai-Girls')),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='Ai-Girls')),
                ('subscription_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tips', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online_status', models.BooleanField(default=False)),
                ('last_active', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('likes_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='girl_photos')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('comments', models.PositiveIntegerField(default=0)),
                ('share', models.PositiveIntegerField(default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rest.girls')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='gallery_videos')),
                ('girl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='rest.girls')),
            ],
        ),
    ]
