# Generated by Django 5.0.6 on 2024-05-22 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_boo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bae',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
