# Generated by Django 5.0.6 on 2024-05-26 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0005_alter_video_video_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bae',
        ),
        migrations.DeleteModel(
            name='Boo',
        ),
    ]
