# Generated by Django 5.0.6 on 2024-05-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0006_delete_bae_delete_boo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='girl_photoss'),
        ),
    ]
