# Generated by Django 4.2.6 on 2024-06-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0008_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='girl_photos'),
        ),
    ]
