# Generated by Django 5.0.6 on 2024-10-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('uid_number', models.CharField(max_length=50)),
                ('parent_contact', models.CharField(max_length=20)),
                ('parent_email', models.EmailField(max_length=254)),
                ('student_class', models.CharField(max_length=50)),
                ('date_registered', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
