# Generated by Django 5.0.6 on 2024-10-29 17:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_student_date_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
