# Generated by Django 5.0.6 on 2024-10-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_date_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
