# Generated by Django 5.0.6 on 2024-11-03 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('route', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
